# Generated by Django 3.1.2 on 2022-04-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0002_courier_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='test',
        ),
    ]
